config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" , registrations: "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/' => 'home#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "home#index"

  resources :teachers, only: [:update]
  resources :school_classes, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :lessons, only: [:new, :create, :update, :destroy]
    resources :events, only: [:create, :update, :destroy]
    resources :date_items, only: [:new, :create, :edit, :update, :destroy]
    resources :class_leaving_time, only: [:create, :update, :destroy]
    resources :morning_activities, only: [:create, :update, :destroy]
    resources :break_activities, only: [:create, :update, :destroy]
    resources :lesson_wdays, only: [:create, :update]
    resources :lesson_periods, only: [:create, :update]
    resources :break_act_displays, only: [:create, :update]
    resources :grade_subject_units, only: [:index]
    resources :using_texts, only: [:index]
    resources :text_books, only: [:show]
    resources :template_lessons, only: [:index, :create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
    resources :template_morning_activities, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
       end
    end
    resources :template_break_activities, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
       end
    end
    resources :template_date_items, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
    resources :template_class_leaving_times, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
  end

resources :school_class_teachers, only: [:create, :destroy]

  get 'school_classes/:token/share', to: 'share#index', as: 'school_class_share_index'
  get 'school_classes/:token/share_teachers', to:'share_teachers#index', as: 'school_class_share_teacher'

  resources :assigned_subjects, only: [:new, :create, :destroy]
  resources :grade_subject_units, only: [:create, :update, :destroy]
  resources :opinions, only: [:index]
  resources :grade_subject, only: [:index]

  get '/get_grade_subject_units', to: 'grade_subject_unit#get_grade_subject_units'
  get '/new_user_session_with_follow', to: 'get_session#sign_in'
  get '/new_user_registration_with_follow', to: 'get_session#sign_up'

end

app/controllers/share_controller.rb
class ShareController < ApplicationController
    after_action :allow_iframe
    def index
        @header_hidden = true
        @school_class = SchoolClass.find_by(token: params[:token])
        @grade_id = @school_class.grade.id
        date = Date.today
        @start_of_week = date.beginning_of_week
        pramas_exist =false
        if params[:start_of_week]
            @start_of_week = params[:start_of_week].to_date
            params_exist = true
        end

        @break_act_display = @school_class.break_act_display
        if @break_act_display
            @has_break_act = @school_class.break_act_display.display
        else
            @break_act_display = BreakActDisplay.new
            @has_break_act = false
        end


        next_week_permission(@start_of_week, params_exist)
        @end_of_week = @start_of_week.end_of_week


        lesson_wday = LessonWday.where(school_class_id: @school_class.id, start_of_week: @start_of_week).first
        if lesson_wday
            @display_wday = []
            @display_wday << 1 if lesson_wday.monday
            @display_wday << 2 if lesson_wday.tuesday
            @display_wday << 3 if lesson_wday.wednesday
            @display_wday << 4 if lesson_wday.thursday
            @display_wday << 5 if lesson_wday.friday
            @display_wday << 6 if lesson_wday.saturday
            @display_wday << 0 if lesson_wday.sunday
        else
            @display_wday = [1,2,3,4,5]
        end

        @lesson_period = @school_class.lesson_period
        if @lesson_period
            @start_of_period = @lesson_period.start_of_period
            @end_of_period = @lesson_period.end_of_period
        else
            @lesson_period = LessonPeriod.new
            @start_of_period = 1
            @end_of_period = 6
        end

        @this_week_events = @school_class.events.where(date: @start_of_week..@end_of_week)
        @this_week_lessons = @school_class.lessons.where(date: @start_of_week..@end_of_week)
        @this_week_date_items = @school_class.date_items.where(date: @start_of_week..@end_of_week)
        @this_week_class_leaving_times = @school_class.class_leaving_times.where(date: @start_of_week..@end_of_week)
        @this_week_morning_activities = @school_class.morning_activities.where(date: @start_of_week..@end_of_week)
        @this_week_break_activities = @school_class.break_activities.where(date: @start_of_week..@end_of_week)

    end

    private
    def allow_iframe
        response.headers['X-Frame-Options'] = 'ALLOWALL'
    end

    def next_week_permission(start_of_week, params_exist)
        today = Date.today
        current_time = Time.now
        wday_of_today = today.wday
        days_until_friday = if today.saturday?
                                -1
                            elsif today.sunday?
                                -2
                            else
                                (5 - today.wday + 7) % 7
                            end
        this_friday = today + days_until_friday
        switch_time = Time.new(this_friday.year, this_friday.month, this_friday.day, 18, 0, 0)
        days_difference = (this_friday - start_of_week).to_i
        if wday_of_today >= 1 && wday_of_today <= 4
            if days_difference == 4
                @next_week_perm = false
            else
                @next_week_perm = true
            end
        elsif wday_of_today == 5 && current_time < switch_time
            if days_difference == 4
                @next_week_perm = false
            else
                @next_week_perm = true
            end
        else
            if params_exist
                if days_difference < 0
                    @next_week_perm = false
                else
                    @next_week_perm = true
                end
            else
                @next_week_perm = false
                @start_of_week = start_of_week + 7
            end
        end
    end
end

app/views/share/_lesson_column.html.haml
%tr.row_lesson
    %td.column_left #{period}
    - (@start_of_week..@end_of_week).each do |date|
        - next unless @display_wday.include?(date.wday)
        - lesson = @this_week_lessons.find_by(date: date, period: period)
        - if lesson
            - if lesson.grade_subject_unit
                - unit_name = lesson.grade_subject_unit.unit_name
                - got_unit_id = lesson.grade_subject_unit.id
            - else
                - unit_name = "&nbsp;".html_safe
                - got_unit_id
            %td
                .iframe_lesson_box
                    .got_lesson
                        %p.lesson_subject #{lesson.grade_subject_name(@grade_id)}
                        %p.lesson_unit #{unit_name}
        - else
            %td.share_grey

app/views/share/index.html.haml
.iframe_class_page_top
    .iframe_class_name
        - if @school_class.grade_id ==1 or @school_class.grade_id ==2
            %p.class_name_display #{@school_class.grade_class}&nbsp;じかんわり
        - else
            %p.class_name_display #{@school_class.grade_class}&nbsp;時間割
    .week_nav
        = link_to school_class_share_index_path(start_of_week: @start_of_week - 1.week) do
            %i.fa-solid.fa-angle-left.week_btn
        - if @next_week_perm
            = link_to school_class_share_index_path(start_of_week: @start_of_week + 1.week) do
                %i.fa-solid.fa-angle-right.week_btn
.iframe_table_box
    %table.class_weekly
        %tr.row_date
            %th
            - (@start_of_week..@end_of_week).each do |date|
                - next unless @display_wday.include?(date.wday)
                %th.column_date  #{date.strftime('%m月%d日')}<br/>#{l(date, format: :abbr_day_name)}
        %tr.row_event
            - if @school_class.grade_id ==1 or @school_class.grade_id ==2
                %td.column_left ぎょうじ
            - else
                %td.column_left 行事予定
            - (@start_of_week..@end_of_week).each do |date|
                - next unless @display_wday.include?(date.wday)
                %td.column_event
                    .event_box
                        - event = @this_week_events.find_by(date: date)
                        - if event
                            %p.event_display  #{event.event_name.html_safe}
        %tr.row_morning_act
            - if @school_class.grade_id ==1
                %td.column_left あさ
            - else
                %td.column_left 朝
            - (@start_of_week..@end_of_week).each do |date|
                - next unless @display_wday.include?(date.wday)
                %td.column_morning_act
                    .morning_act_box{id: "#{date}"}
                        - morning_act = @this_week_morning_activities.find_by(date: date)
                        - if morning_act
                            %p.morning_act_display  #{morning_act.activity_name.html_safe}
        - (@start_of_period..4).each do |period|
            = render partial: 'lesson_column', locals: { period: period }
        - if @has_break_act
            %tr.row_break_act
                - if @school_class.grade_id ==1
                    %td.column_left ひる
                - else
                    %td.column_left 昼
                - (@start_of_week..@end_of_week).each do |date|
                    - next unless @display_wday.include?(date.wday)
                    %td.column_break_act
                        .break_act_box{id: "#{date}"}
                            - break_act = @this_week_break_activities.find_by(date: date)
                            - if break_act
                                %p.break_act_display  #{break_act.activity_name.html_safe}
        - (5..@end_of_period).each do |period|
            = render partial: 'lesson_column', locals: { period: period }
        %tr.row_item
            - if @school_class.grade_id ==1 or @school_class.grade_id ==2
                %td.column_left もちもの
            - else
                %td.column_left 持ち物
            - (@start_of_week..@end_of_week).each do |date|
                - next unless @display_wday.include?(date.wday)
                %td.column_item
                    .item_box
                        - item = @this_week_date_items.find_by(date: date)
                        - if item
                            %p.item_display  #{item.item_name.html_safe}
        %tr.row_leaving
            - if @school_class.grade_id ==1
                %td.column_left げこう
            - else
                %td.column_left 下校
            - (@start_of_week..@end_of_week).each do |date|
                - next unless @display_wday.include?(date.wday)
                %td
                    .leaving_time_box
                        - leaving_time = @this_week_class_leaving_times.find_by(date: date)
                        - if leaving_time
                            %p.leaving_time_display  #{leaving_time.leaving_time.strftime("%H:%M")}

= javascript_pack_tag 'iframe'