config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" , registrations: "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/' => 'home#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "home#index"

  resources :teachers, only: [:update]
  resources :school_classes, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :lessons, only: [:new, :create, :update, :destroy]
    resources :events, only: [:create, :update, :destroy]
    resources :date_items, only: [:new, :create, :edit, :update, :destroy]
    resources :class_leaving_time, only: [:create, :update, :destroy]
    resources :morning_activities, only: [:create, :update, :destroy]
    resources :break_activities, only: [:create, :update, :destroy]
    resources :lesson_wdays, only: [:create, :update]
    resources :lesson_periods, only: [:create, :update]
    resources :break_act_displays, only: [:create, :update]
    resources :grade_subject_units, only: [:index]
    resources :using_texts, only: [:index]
    resources :text_books, only: [:show]
    resources :template_lessons, only: [:index, :create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
    resources :template_morning_activities, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
       end
    end
    resources :template_break_activities, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
       end
    end
    resources :template_date_items, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
    resources :template_class_leaving_times, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
  end

resources :school_class_teachers, only: [:create, :destroy]

  get 'school_classes/:token/share', to: 'share#index', as: 'school_class_share_index'
  get 'school_classes/:token/share_teachers', to:'share_teachers#index', as: 'school_class_share_teacher'

  resources :assigned_subjects, only: [:new, :create, :destroy]
  resources :grade_subject_units, only: [:create, :update, :destroy]
  resources :opinions, only: [:index]
  resources :grade_subject, only: [:index]

  get '/get_grade_subject_units', to: 'grade_subject_unit#get_grade_subject_units'
  get '/new_user_session_with_follow', to: 'get_session#sign_in'
  get '/new_user_registration_with_follow', to: 'get_session#sign_up'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render 'home/index'
    end
end

app/views/home/index.html.haml
.container
    .page_title_box
        %h1 School Notes
        %h2.page_title_sub 時間割作成・共有をカンタンに
        .page_btn_box
            = link_to "登録", new_user_registration_path, class: "sign_up_btn"
            .sign_in_btn_box
                = link_to "ログイン", user_session_path, class: "sign_in_btn"
                = link_to "ゲストログインはこちら", users_guest_sign_in_path, method: :post, class: "sign_in_guest"
    .page_explain_box.page_explain_grey
        .page_explain_child
            %h3.page_explain_child_t 入れ替え機能
            = image_tag 'dragdrop.gif', class: "explain_gif"
            %p.page_explain_p ドラッグ&ドロップ１回の操作でコマの入れ替えが完了します。
        .page_explain_child
            %h3.page_explain_child_t テンプレート機能
            = image_tag 'template.gif', class: "explain_gif"
            %p.page_explain_p ワンクリックでいつもの時間割が作成できます。
        .page_explain_child
            %h3.page_explain_child_t 自動調整・自動保存
            = image_tag 'auto.png', class: "explain_gif"
            %p.page_explain_p 自動的に字の大きさや行間を調整し、自動的に保存します。
    .page_explain_box
        .page_explain_left
            = image_tag 'share_cloud.jpg', class: "explain_image"
        .page_explain_right
            %h3.page_explain_title ノンステップで時間割を共有しましょう
            .page_explain-sentences
                %p 時間割は作って終わりではありませんよね。関係の先生方に見せて調整し、子供達に配布し、ホームページに貼り付けて…。そんな煩わしい手間からはおさらばしましょう。
                %p School Noteでは、共有用のURLを１回教えれば、あとは必要な時にアクセスしてもらうだけ。同僚や子供たち、親御さんと最新の時間割を共有できます。
                %p 埋め込みコードを利用して学校ホームページ等に掲載することもできます。
                %p 共有のためにあなたが毎週すべきことは何もありません。
                %p もちろん印刷したい時は、ワンクリックで完璧なレイアウトに仕上げてくれます。
    .page_title_box.page_explain_grey
        %h2.page_title_sub さあ今すぐ無料ではじめよう
        .page_title_sentence
            %p 業者や情報担当者の設定を待つ必要はありません。
            %p お持ちのgoogleアカウントやMicrosoftアカウントで今すぐサインアップして利用を開始できます。
        .page_btn_box
            = link_to "登録", new_user_registration_path, class: "sign_up_btn"