config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" , registrations: "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/' => 'home#index'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "home#index"

  resources :teachers, only: [:update]
  resources :school_classes, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :lessons, only: [:new, :create, :update, :destroy]
    resources :events, only: [:create, :update, :destroy]
    resources :date_items, only: [:new, :create, :edit, :update, :destroy]
    resources :class_leaving_time, only: [:create, :update, :destroy]
    resources :morning_activities, only: [:create, :update, :destroy]
    resources :break_activities, only: [:create, :update, :destroy]
    resources :lesson_wdays, only: [:create, :update]
    resources :lesson_periods, only: [:create, :update]
    resources :break_act_displays, only: [:create, :update]
    resources :grade_subject_units, only: [:index]
    resources :using_texts, only: [:index]
    resources :text_books, only: [:show]
    resources :template_lessons, only: [:index, :create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
    resources :template_morning_activities, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
       end
    end
    resources :template_break_activities, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
       end
    end
    resources :template_date_items, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
    resources :template_class_leaving_times, only: [:create, :update, :destroy] do
      collection do
        get 'get_temp'
      end
    end
  end

resources :school_class_teachers, only: [:create, :destroy]

  get 'school_classes/:token/share', to: 'share#index', as: 'school_class_share_index'
  get 'school_classes/:token/share_teachers', to:'share_teachers#index', as: 'school_class_share_teacher'

  resources :assigned_subjects, only: [:new, :create, :destroy]
  resources :grade_subject_units, only: [:create, :update, :destroy]
  resources :opinions, only: [:index]
  resources :grade_subject, only: [:index]

  get '/get_grade_subject_units', to: 'grade_subject_unit#get_grade_subject_units'
  get '/new_user_session_with_follow', to: 'get_session#sign_in'
  get '/new_user_registration_with_follow', to: 'get_session#sign_up'

end

app/controllers/share_teachers_controller.rb
class ShareTeachersController < ApplicationController

    def index
        @school_class = SchoolClass.find_by(token: params[:token])
        @token = @school_class.token
        @grade_id = @school_class.grade.id
        @hiding_menu_btn = true
        gon.school_class_id = @school_class.id
        date = Date.today
        @start_of_week = date.beginning_of_week
        pramas_exist =false
        if params[:start_of_week]
            @start_of_week = params[:start_of_week].to_date
            params_exist = true
        end
        @end_of_week = @start_of_week.end_of_week

        @break_act_display = @school_class.break_act_display
        if @break_act_display
            @has_break_act = @school_class.break_act_display.display
        else
            @break_act_display = BreakActDisplay.new
            @has_break_act = false
        end

        @main_teacher_name = SchoolClassTeacher.find_by(school_classes_id: @school_class.id).teacher.display_name
        if user_signed_in?
            @class_teacher = SchoolClassTeacher.find_by(school_classes_id: @school_class.id, teachers_id: current_user.teacher.id)
        end

        lesson_wday = LessonWday.where(school_class_id: @school_class.id, start_of_week: @start_of_week).first
        if lesson_wday
            @display_wday = []
            @display_wday << 1 if lesson_wday.monday
            @display_wday << 2 if lesson_wday.tuesday
            @display_wday << 3 if lesson_wday.wednesday
            @display_wday << 4 if lesson_wday.thursday
            @display_wday << 5 if lesson_wday.friday
            @display_wday << 6 if lesson_wday.saturday
            @display_wday << 0 if lesson_wday.sunday
        else
            @display_wday = [1,2,3,4,5]
        end
        @lesson_period = @school_class.lesson_period
        if @lesson_period
            @start_of_period = @lesson_period.start_of_period
            @end_of_period = @lesson_period.end_of_period
        else
            @lesson_period = LessonPeriod.new
            @start_of_period = 1
            @end_of_period = 6
        end

        @this_week_events = @school_class.events.where(date: @start_of_week..@end_of_week)
        @this_week_lessons = @school_class.lessons.where(date: @start_of_week..@end_of_week)
        @this_week_date_items = @school_class.date_items.where(date: @start_of_week..@end_of_week)
        @this_week_class_leaving_times = @school_class.class_leaving_times.where(date: @start_of_week..@end_of_week)
        @this_week_morning_activities = @school_class.morning_activities.where(date: @start_of_week..@end_of_week)
        @this_week_break_activities = @school_class.break_activities.where(date: @start_of_week..@end_of_week)

        if @grade_id == 1 || @grade_id == 2
            @table_title = @school_class.grade_class + " じかんわり" + "(" + @main_teacher_name + "先生)"
        else
            @table_title = @school_class.grade_class + " 時間割" + "(" + @main_teacher_name + "先生)"
        end
    end

end

app/views/share_teachers/_lesson_column.html.haml
%tr.row_lesson
    %td.column_left #{period}
    - (@start_of_week..@end_of_week).each do |date|
        - next unless @display_wday.include?(date.wday)
        - lesson = @this_week_lessons.find_by(date: date, period: period)
        - if lesson
            - if lesson.grade_subject_unit
                - unit_name = lesson.grade_subject_unit.unit_name
                - got_unit_id = lesson.grade_subject_unit.id
            - else
                - unit_name = "&nbsp;".html_safe
                - got_unit_id
            %td.column_lesson
                .lesson_box_for_share
                    .got_lesson
                        %p.lesson_subject #{lesson.grade_subject_name(@grade_id)}
                        %p.lesson_unit #{unit_name}
        - else
            %td.share_grey

app/views/share_teachers/index.html.haml
- if user_signed_in?
    - if not @class_teacher
        .top_container
            .top_info_box
                %p.top_info #{@main_teacher_name}先生の時間割をフォローしませんか。
            .top_btn_box
                = link_to "フォロー",school_class_teachers_path(class_token: @token) , method: :post, class: "sign_up_btn"
- else
    .top_container
        .top_info_box
            %p.top_info 時間割をカンタンに作成・共有できるSchool Notesに登録しませんか。
            %p.top_info #{@main_teacher_name}先生の時間割もフォローしていつでも確認できるようになります。
        .top_btn_box
            = link_to "登録", new_user_registration_with_follow_path(class_token: @token), class: "sign_up_btn top_sign_up_btn"
            = link_to "ログイン&フォロー", new_user_session_with_follow_path(class_token: @token), class: "sign_in_btn top_sign_in_btn"
.container
    .schedule_container
        .schedule_nav
            .left_nav
                %i.fa-solid.fa-bars.week_btn.menu_btn.hidden
                .week_nav
                    = link_to school_class_share_teacher_path(start_of_week: @start_of_week - 1.week) do
                        %i.fa-solid.fa-angle-left.week_btn
                    = link_to school_class_share_teacher_path(start_of_week: @start_of_week + 1.week) do
                        %i.fa-solid.fa-angle-right.week_btn
            .right_nav
                %i.fa-solid.fa-print.right_nav_btn.print_btn{data: {table_title: @table_title}}
                %i.fa-solid.fa-file-image.right_nav_btn.image_download_btn{data: {start_of_week: @start_of_week, end_of_week: @end_of_week, class_name: @school_class.grade_class}}
        .table_box
            %table.class_weekly
                %tr.row_date
                    %th.column_left
                    - (@start_of_week..@end_of_week).each do |date|
                        - next unless @display_wday.include?(date.wday)
                        %th.column_date  #{date.strftime('%m月%d日')}<br/>#{l(date, format: :abbr_day_name)}
                %tr.row_event
                    - if @school_class.grade_id ==1 or @school_class.grade_id ==2
                        %td.column_left ぎょうじ
                    - else
                        %td.column_left 行事予定
                    - (@start_of_week..@end_of_week).each do |date|
                        - next unless @display_wday.include?(date.wday)
                        %td.column_event
                            .event_box
                                - event = @this_week_events.find_by(date: date)
                                - if event
                                    %p.event_display #{event.event_name.html_safe}
                %tr.row_morning_act
                    - if @school_class.grade_id ==1
                        %td.column_left あさ
                    - else
                        %td.column_left 朝
                    - (@start_of_week..@end_of_week).each do |date|
                        - next unless @display_wday.include?(date.wday)
                        %td.column_morning_act
                            .morning_act_box
                                - morning_act = @this_week_morning_activities.find_by(date: date)
                                - if morning_act
                                    %p.morning_act_display  #{morning_act.activity_name.html_safe}
                - (@start_of_period..4).each do |period|
                    = render partial: 'lesson_column', locals: { period: period }
                - if @has_break_act
                    %tr.row_break_act
                        - if @school_class.grade_id ==1
                            %td.column_left ひる
                        - else
                            %td.column_left 昼
                        - (@start_of_week..@end_of_week).each do |date|
                            - next unless @display_wday.include?(date.wday)
                            %td.column_break_act
                                .break_act_box{id: "#{date}"}
                                    - break_act = @this_week_break_activities.find_by(date: date)
                                    - if break_act
                                        %p.break_act_display  #{break_act.activity_name.html_safe}
                - (5..@end_of_period).each do |period|
                    = render partial: 'lesson_column', locals: { period: period }
                %tr.row_item
                    - if @school_class.grade_id ==1 or @school_class.grade_id ==2
                        %td.column_left もちもの
                    - else
                        %td.column_left 持ち物
                    - (@start_of_week..@end_of_week).each do |date|
                        - next unless @display_wday.include?(date.wday)
                        %td.column_item
                            .item_box
                                - item = @this_week_date_items.find_by(date: date)
                                - if item
                                    %p.item_display #{item.item_name.html_safe}
                %tr.row_leaving
                    - if @school_class.grade_id ==1
                        %td.column_left げこう
                    - else
                        %td.column_left 下校
                    - (@start_of_week..@end_of_week).each do |date|
                        - next unless @display_wday.include?(date.wday)
                        %td
                            .leaving_time_box{id: "#{date}"}
                                - leaving_time = @this_week_class_leaving_times.find_by(date: date)
                                - if leaving_time
                                    %p.leaving_time_display  #{leaving_time.leaving_time.strftime("%H:%M")}
    = javascript_pack_tag 'share_teacher'